require_relative 'graph_search'

graph = GraphSearch.new

alicia_silverstone = Node.new('Alicia Silverstone')
al_pacino = Node.new('Al Pacino')
andre_the_giant = Node.new('Andre The Giant')
angela_bassett = Node.new('Angela Bassett')
angourie_rice = Node.new('Angourie Rice')
ann_wolfe = Node.new('Ann Wolfe')
antonio_banderas = Node.new('Antonio Banderas')
armelia_mcqueen = Node.new('Armelia Mcqueen')
ashley_green = Node.new('Ashley Green')
ashley_judd = Node.new('Ashley Judd')
ben_affleck = Node.new('Ben Affleck')
bernie_mac = Node.new('Bernie Mac')
billy_burke = Node.new('Billy Burke')
billy_crystal = Node.new('Billy Crystal')
bokeem_woodbine = Node.new('Bokeem Woodbine')
brad_pitt = Node.new('Brad Pitt')
bruce_willis = Node.new('Bruce Willis')
bryce_wilson = Node.new('Bryce Wilson')
carrie_anne_moss = Node.new('Carrie Anne Moss')
cary_elwes = Node.new('Cary Elwes')
casey_affleck = Node.new('Casey Affleck')
chadwick_boseman = Node.new('Chadwick Boseman')
chris_odonnell = Node.new('Chris Odonnell')
chris_pine = Node.new('Chris Pine')
christian_slater = Node.new('Christian Slater')
christopher_walken = Node.new('Christopher Walken')
chris_tucker = Node.new('Chris Tucker')
clifton_powell = Node.new('Clifton Powell')
collin_farrell = Node.new('Collin Farrell')
connie_nielsen = Node.new('Connie Nielsen')
cuba_gooding_jr = Node.new('Cuba Gooding Jr')
dakota_fanning = Node.new('Dakota Fanning')
dakota_johnson = Node.new('Dakota Johnson')
danai_gurira = Node.new('Danai Gurira')
danny_glover = Node.new('Danny Glover')
demi_moore = Node.new('Demi Moore')
denzel_washington = Node.new('Denzel Washington')
djimon_hounsou = Node.new('Djimon Hounsou')
donald_sutherland = Node.new('Donald Sutherland')
dustin_hoffman = Node.new('Dustin Hoffman')
eddie_murphy = Node.new('Eddie Murphy')
elijah_wood = Node.new('Elijah Wood')
elisabeth_shue = Node.new('Elisabeth Shue')
elizabeth_banks = Node.new('Elizabeth Banks')
elle_fanning = Node.new('Elle Fanning')
erik_king = Node.new('Erik King')
gal_gadot = Node.new('Gal Gadot')
gary_busey = Node.new('Gary Busey')
gary_oldman = Node.new('Gary Oldman')
gloria_foster = Node.new('Gloria Foster')
hayden_panettiere = Node.new('Hayden Panettiere')
hugo_weaving = Node.new('Hugo Weaving')
ian_holm = Node.new('Ian Holm')
ice_cube = Node.new('Ice Cube')
jackie_swanson = Node.new('Jackie Swanson')
jamie_dornan = Node.new('Jamie Dornan')
jamie_foxx = Node.new('Jamie Foxx')
jason_patric = Node.new('Jason Patric')
jennifer_lawrence = Node.new('Jennifer Lawrence')
jessica_biel = Node.new('Jessica Biel')
jim_carrey = Node.new('Jim Carrey')
joan_cusack = Node.new('Joan Cusack')
joe_pesci = Node.new('Joe Pesci')
joey_cramer = Node.new('Joey Cramer')
josh_brolin = Node.new('Josh Brolin')
josh_duhamel = Node.new('Josh Duhamel')
kate_beckinsale = Node.new('Kate Beckinsale')
keanu_reeves = Node.new('Keanu Reeves')
keith_david = Node.new('Keith David')
kerry_washington = Node.new('Kerry Washington')
kevin_bacon = Node.new('Kevin Bacon')
kevin_costner = Node.new('Kevin Costner')
kevin_grevioux = Node.new('Kevin Grevioux')
kevin_spacey = Node.new('Kevin Spacey')
kim_cattrall = Node.new('Kim Cattrall')
kim_dickens = Node.new('Kim Dickens')
kirsten_dunst = Node.new('Kirsten Dunst')
kris_kristofferson = Node.new('Kris Kristofferson')
kristen_stewart = Node.new('Kristen Stewart')
larenz_tate = Node.new('Larenz Tate')
laurence_fishburne = Node.new('Laurence Fishburne')
liam_hemsworth = Node.new('Liam Hemsworth')
liv_tyler = Node.new('Liv Tyler')
luke_grimes = Node.new('Luke Grimes')
lupita_nyongo = Node.new('Lupita Nyongo')
mandy_patinkin = Node.new('Mandy Patinkin')
marc_anthony = Node.new('Marc Anthony')
marcia_gay_harden = Node.new('Marcia Gay Harden')
mark_wahlberg = Node.new('Mark Wahlberg')
martin_lawrence = Node.new('Martin Lawrence')
matt_damon = Node.new('Matt Damon')
matthew_mcconaughey = Node.new('Matthew Mcconaughey')
mel_gibson = Node.new('Mel Gibson')
michael_b_jordan = Node.new('Michael B Jordan')
michael_clarke_duncan = Node.new('Michael Clarke Duncan')
michael_sheen = Node.new('Michael Sheen')
michelle_trachtenberg = Node.new('Michelle Trachtenberg')
milla_jovovich = Node.new('Milla Jovovich')
minnie_driver = Node.new('Minnie Driver')
mitchell_ryan = Node.new('Mitchell Ryan')
morris_chestnut = Node.new('Morris Chestnut')
natalie_portman = Node.new('Natalie Portman')
nbushe_wright = Node.new('Nbushe Wright')
nicole_kidman = Node.new('Nicole Kidman')
obba_babatunde = Node.new('Obba Babatunde')
octavia_spencer = Node.new('Octavia Spencer')
olivia_williams = Node.new('Olivia Williams')
orlando_bloom = Node.new('Orlando Bloom')
patrick_swayze = Node.new('Patrick Swayze')
paul_reubens = Node.new('Paul Reubens')
peter_cullen = Node.new('Peter Cullen')
queen_latifah = Node.new('Queen Latifah')
rachel_weisz = Node.new('Rachel Weisz')
radha_mitchell = Node.new('Radha Mitchell')
raymond_forchion = Node.new('Raymond Forchion')
regina_king = Node.new('Regina King')
rhona_mitra = Node.new('Rhona Mitra')
rick_james = Node.new('Rick James')
rita_ora = Node.new('Rita Ora')
robert_de_niro = Node.new('Robert De Niro')
robert_pattinson = Node.new('Robert Pattinson')
robin_williams = Node.new('Robin Williams')
robin_wright = Node.new('Robin Wright')
ron_perlman = Node.new('Ron Perlman')
ryan_reynolds = Node.new('Ryan Reynolds')
samuel_l_jackson = Node.new('Samuel L Jackson')
sandra_bullock = Node.new('Sandra Bullock')
sarah_jessica_parker = Node.new('Sarah Jessica Parker')
scott_speedman = Node.new('Scott Speedman')
shia_labeouf = Node.new('Shia Labeouf')
steve_buscemi = Node.new('Steve Buscemi')
taylor_lautner = Node.new('Taylor Lautner')
terrence_howard = Node.new('Terrence Howard')
theo_james = Node.new('Theo James')
tilda_swinton = Node.new('Tilda Swinton')
tom_cruise = Node.new('Tom Cruise')
tommy_lee_jones = Node.new('Tommy Lee Jones')
tom_petty = Node.new('Tom Petty')
tony_goldwyn = Node.new('Tony Goldwyn')
tyrese_gibson = Node.new('Tyrese Gibson')
val_kilmer = Node.new('Val Kilmer')
veronica_cartwright = Node.new('Veronica Cartwright')
viggo_mortensen = Node.new('Viggo Mortensen')
walter_matthau = Node.new('Walter Matthau')
wesley_snipes = Node.new('Wesley Snipes')
whoopi_goldberg = Node.new('Whoopi Goldberg')
will_patton = Node.new('Will Patton')
woody_harrelson = Node.new('Woody Harrelson')

alicia_silverstone.film_actor_hash['Beauty Shop'] = [ kevin_bacon, queen_latifah, djimon_hounsou, bryce_wilson ]
al_pacino.film_actor_hash['Heat'] = [ ashley_judd, robert_de_niro, val_kilmer, natalie_portman ]
andre_the_giant.film_actor_hash['The Princess Bride'] = [ cary_elwes, robin_wright, mandy_patinkin, billy_crystal ]
angela_bassett.film_actor_hash['Black Panther'] = [ danai_gurira, lupita_nyongo, michael_b_jordan, chadwick_boseman ]
angela_bassett.film_actor_hash['Boyz n the Hood'] = [ ice_cube, cuba_gooding_jr, morris_chestnut, laurence_fishburne ]
angourie_rice.film_actor_hash['Beguiled'] = [ nicole_kidman, elle_fanning, kirsten_dunst, collin_farrell ]
ann_wolfe.film_actor_hash['Wonder Woman'] = [ gal_gadot, chris_pine, robin_wright, connie_nielsen ]
antonio_banderas.film_actor_hash['Interview with the Vampire'] = [ brad_pitt, christian_slater, kirsten_dunst, tom_cruise ]
armelia_mcqueen.film_actor_hash['Ghost'] = [ demi_moore, patrick_swayze, whoopi_goldberg, tony_goldwyn ]
ashley_green.film_actor_hash['Twilight'] = [ kristen_stewart, robert_pattinson, taylor_lautner, billy_burke ]
ashley_judd.film_actor_hash['Heat'] = [ val_kilmer, robert_de_niro, al_pacino, natalie_portman ]
ben_affleck.film_actor_hash['Armageddon'] = [ michael_clarke_duncan, liv_tyler, bruce_willis, steve_buscemi ]
ben_affleck.film_actor_hash['Good Will Hunting'] = [ matt_damon, robin_williams, minnie_driver, casey_affleck ]
bernie_mac.film_actor_hash['Life'] = [ rick_james, martin_lawrence, eddie_murphy, obba_babatunde ]
billy_burke.film_actor_hash['Twilight'] = [ kristen_stewart, robert_pattinson, taylor_lautner, ashley_green ]
billy_crystal.film_actor_hash['The Princess Bride'] = [ cary_elwes, robin_wright, mandy_patinkin, andre_the_giant ]
bokeem_woodbine.film_actor_hash['Ray'] = [ jamie_foxx, kerry_washington, regina_king, clifton_powell ]
brad_pitt.film_actor_hash['Interview with the Vampire'] = [ tom_cruise, kirsten_dunst, christian_slater, antonio_banderas ]
brad_pitt.film_actor_hash['Sleepers'] = [ robert_de_niro, kevin_bacon, dustin_hoffman, jason_patric ]
bruce_willis.film_actor_hash['Armageddon'] = [ steve_buscemi, liv_tyler, ben_affleck, michael_clarke_duncan ]
bruce_willis.film_actor_hash['The Fifth Element'] = [ milla_jovovich, ian_holm, gary_oldman, chris_tucker ]
bryce_wilson.film_actor_hash['Beauty Shop'] = [ queen_latifah, kevin_bacon, djimon_hounsou, alicia_silverstone ]
carrie_anne_moss.film_actor_hash['The Matrix'] = [ keanu_reeves, laurence_fishburne, gloria_foster, hugo_weaving ]
cary_elwes.film_actor_hash['The Princess Bride'] = [ robin_wright, andre_the_giant, mandy_patinkin, billy_crystal ]
casey_affleck.film_actor_hash['Good Will Hunting'] = [ matt_damon, robin_williams, ben_affleck, minnie_driver ]
chadwick_boseman.film_actor_hash['Black Panther'] = [ michael_b_jordan, lupita_nyongo, danai_gurira, angela_bassett ]
chris_odonnell.film_actor_hash['Batman Forever'] = [ val_kilmer, tommy_lee_jones, jim_carrey, nicole_kidman ]
chris_pine.film_actor_hash['Wonder Woman'] = [ gal_gadot, robin_wright, ann_wolfe, connie_nielsen ]
christian_slater.film_actor_hash['Interview with the Vampire'] = [ tom_cruise, brad_pitt, kirsten_dunst, antonio_banderas ]
christopher_walken.film_actor_hash['Man on Fire'] = [ marc_anthony, denzel_washington, radha_mitchell, dakota_fanning ]
chris_tucker.film_actor_hash['Dead Presidents'] = [ terrence_howard, larenz_tate, keith_david, nbushe_wright ]
chris_tucker.film_actor_hash['The Fifth Element'] = [ milla_jovovich, bruce_willis, gary_oldman, ian_holm ]
clifton_powell.film_actor_hash['Ray'] = [ jamie_foxx, kerry_washington, regina_king, bokeem_woodbine ]
collin_farrell.film_actor_hash['Beguiled'] = [ nicole_kidman, elle_fanning, kirsten_dunst, angourie_rice ]
connie_nielsen.film_actor_hash['Wonder Woman'] = [ gal_gadot, chris_pine, robin_wright, ann_wolfe ]
cuba_gooding_jr.film_actor_hash['Boyz n the Hood'] = [ ice_cube, morris_chestnut, angela_bassett, laurence_fishburne ]
dakota_fanning.film_actor_hash['Man on Fire'] = [ radha_mitchell, denzel_washington, marc_anthony, christopher_walken ]
dakota_johnson.film_actor_hash['Fifty Shades of Grey'] = [ marcia_gay_harden, jamie_dornan, rita_ora, luke_grimes ]
danai_gurira.film_actor_hash['Black Panther'] = [ chadwick_boseman, lupita_nyongo, michael_b_jordan, angela_bassett ]
danny_glover.film_actor_hash['Lethal Weapon'] = [ mel_gibson, mitchell_ryan, gary_busey, jackie_swanson ]
demi_moore.film_actor_hash['Ghost'] = [ whoopi_goldberg, patrick_swayze, armelia_mcqueen, tony_goldwyn ]
denzel_washington.film_actor_hash['Man on Fire'] = [ marc_anthony, dakota_fanning, radha_mitchell, christopher_walken ]
djimon_hounsou.film_actor_hash['Beauty Shop'] = [ queen_latifah, kevin_bacon, alicia_silverstone, bryce_wilson ]
djimon_hounsou.film_actor_hash['Constantine'] = [ keanu_reeves, rachel_weisz, tilda_swinton, shia_labeouf ]
donald_sutherland.film_actor_hash['The Hunger Games'] = [ woody_harrelson, liam_hemsworth, elizabeth_banks, jennifer_lawrence ]
dustin_hoffman.film_actor_hash['Sleepers'] = [ robert_de_niro, kevin_bacon, jason_patric, brad_pitt ]
eddie_murphy.film_actor_hash['Life'] = [ rick_james, martin_lawrence, bernie_mac, obba_babatunde ]
elijah_wood.film_actor_hash['The Lord of the Rings'] = [ liv_tyler, orlando_bloom, viggo_mortensen, ian_holm ]
elisabeth_shue.film_actor_hash['Hallow Man'] = [ kevin_bacon, rhona_mitra, josh_brolin, kim_dickens ]
elizabeth_banks.film_actor_hash['The Hunger Games'] = [ woody_harrelson, liam_hemsworth, jennifer_lawrence, donald_sutherland ]
elle_fanning.film_actor_hash['Beguiled'] = [ nicole_kidman, collin_farrell, kirsten_dunst, angourie_rice ]
erik_king.film_actor_hash['Ice Princess'] = [ michelle_trachtenberg, hayden_panettiere, joan_cusack, kim_cattrall ]
gal_gadot.film_actor_hash['Wonder Woman'] = [ robin_wright, chris_pine, ann_wolfe, connie_nielsen ]
gary_busey.film_actor_hash['Lethal Weapon'] = [ mel_gibson, jackie_swanson, danny_glover, mitchell_ryan ]
gary_oldman.film_actor_hash['JFK'] = [ walter_matthau, tommy_lee_jones, joe_pesci, kevin_costner ]
gary_oldman.film_actor_hash['The Fifth Element'] = [ chris_tucker, bruce_willis, milla_jovovich, ian_holm ]
gloria_foster.film_actor_hash['The Matrix'] = [ keanu_reeves, carrie_anne_moss, laurence_fishburne, hugo_weaving ]
hayden_panettiere.film_actor_hash['Ice Princess'] = [ michelle_trachtenberg, kim_cattrall, joan_cusack, erik_king ]
hugo_weaving.film_actor_hash['The Matrix'] = [ keanu_reeves, gloria_foster, laurence_fishburne, carrie_anne_moss ]
ian_holm.film_actor_hash['The Fifth Element'] = [ milla_jovovich, chris_tucker, gary_oldman, bruce_willis ]
ian_holm.film_actor_hash['The Lord of the Rings'] = [ liv_tyler, orlando_bloom, viggo_mortensen, elijah_wood ]
ice_cube.film_actor_hash['Boyz n the Hood'] = [ morris_chestnut, cuba_gooding_jr, angela_bassett, laurence_fishburne ]
jackie_swanson.film_actor_hash['Lethal Weapon'] = [ mel_gibson, danny_glover, gary_busey, mitchell_ryan ]
jamie_dornan.film_actor_hash['Fifty Shades of Grey'] = [ rita_ora, dakota_johnson, marcia_gay_harden, luke_grimes ]
jamie_foxx.film_actor_hash['Ray'] = [ regina_king, kerry_washington, bokeem_woodbine, clifton_powell ]
jason_patric.film_actor_hash['Sleepers'] = [ robert_de_niro, kevin_bacon, dustin_hoffman, brad_pitt ]
jennifer_lawrence.film_actor_hash['The Hunger Games'] = [ woody_harrelson, liam_hemsworth, elizabeth_banks, donald_sutherland ]
jessica_biel.film_actor_hash['Blade'] = [ wesley_snipes, ryan_reynolds, ron_perlman, kris_kristofferson ]
jim_carrey.film_actor_hash['Batman Forever'] = [ val_kilmer, tommy_lee_jones, chris_odonnell, nicole_kidman ]
joan_cusack.film_actor_hash['Ice Princess'] = [ michelle_trachtenberg, hayden_panettiere, kim_cattrall, erik_king ]
joe_pesci.film_actor_hash['JFK'] = [ kevin_costner, tommy_lee_jones, gary_oldman, walter_matthau ]
joey_cramer.film_actor_hash['Flight of the Navigator'] = [ veronica_cartwright, sarah_jessica_parker, paul_reubens, raymond_forchion ]
josh_brolin.film_actor_hash['Hallow Man'] = [ kevin_bacon, elisabeth_shue, rhona_mitra, kim_dickens ]
josh_duhamel.film_actor_hash['Transformers'] = [ tyrese_gibson, mark_wahlberg, peter_cullen, shia_labeouf ]
kate_beckinsale.film_actor_hash['Underworld'] = [ theo_james, kevin_grevioux, scott_speedman, michael_sheen ]
keanu_reeves.film_actor_hash['Constantine'] = [ tilda_swinton, rachel_weisz, djimon_hounsou, shia_labeouf ]
keanu_reeves.film_actor_hash['The Matrix'] = [ laurence_fishburne, carrie_anne_moss, gloria_foster, hugo_weaving ]
keith_david.film_actor_hash['Dead Presidents'] = [ terrence_howard, chris_tucker, larenz_tate, nbushe_wright ]
kerry_washington.film_actor_hash['Ray'] = [ jamie_foxx, regina_king, bokeem_woodbine, clifton_powell ]
kevin_bacon.film_actor_hash['Beauty Shop'] = [ queen_latifah, alicia_silverstone, djimon_hounsou, bryce_wilson ]
kevin_bacon.film_actor_hash['Hallow Man'] = [ rhona_mitra, elisabeth_shue, josh_brolin, kim_dickens ]
kevin_bacon.film_actor_hash['Sleepers'] = [ robert_de_niro, jason_patric, dustin_hoffman, brad_pitt ]
kevin_costner.film_actor_hash['JFK'] = [ gary_oldman, tommy_lee_jones, joe_pesci, walter_matthau ]
kevin_costner.film_actor_hash['The Postman'] = [ will_patton, larenz_tate, olivia_williams, tom_petty ]
kevin_grevioux.film_actor_hash['Underworld'] = [ kate_beckinsale, theo_james, scott_speedman, michael_sheen ]
kevin_spacey.film_actor_hash['A Time To Kill'] = [ octavia_spencer, sandra_bullock, samuel_l_jackson, matthew_mcconaughey ]
kim_cattrall.film_actor_hash['Ice Princess'] = [ michelle_trachtenberg, hayden_panettiere, joan_cusack, erik_king ]
kim_dickens.film_actor_hash['Hallow Man'] = [ kevin_bacon, josh_brolin, rhona_mitra, elisabeth_shue ]
kirsten_dunst.film_actor_hash['Beguiled'] = [ collin_farrell, elle_fanning, angourie_rice, nicole_kidman ]
kirsten_dunst.film_actor_hash['Interview with the Vampire'] = [ tom_cruise, christian_slater, brad_pitt, antonio_banderas ]
kris_kristofferson.film_actor_hash['Blade'] = [ wesley_snipes, ryan_reynolds, ron_perlman, jessica_biel ]
kristen_stewart.film_actor_hash['Twilight'] = [ taylor_lautner, robert_pattinson, billy_burke, ashley_green ]
larenz_tate.film_actor_hash['Dead Presidents'] = [ terrence_howard, chris_tucker, keith_david, nbushe_wright ]
larenz_tate.film_actor_hash['The Postman'] = [ kevin_costner, will_patton, olivia_williams, tom_petty ]
laurence_fishburne.film_actor_hash['Boyz n the Hood'] = [ ice_cube, cuba_gooding_jr, morris_chestnut, angela_bassett ]
laurence_fishburne.film_actor_hash['The Matrix'] = [ keanu_reeves, gloria_foster, carrie_anne_moss, hugo_weaving ]
liam_hemsworth.film_actor_hash['The Hunger Games'] = [ woody_harrelson, jennifer_lawrence, elizabeth_banks, donald_sutherland ]
liv_tyler.film_actor_hash['Armageddon'] = [ michael_clarke_duncan, bruce_willis, ben_affleck, steve_buscemi ]
liv_tyler.film_actor_hash['The Lord of the Rings'] = [ viggo_mortensen, orlando_bloom, ian_holm, elijah_wood ]
luke_grimes.film_actor_hash['Fifty Shades of Grey'] = [ marcia_gay_harden, dakota_johnson, rita_ora, jamie_dornan ]
lupita_nyongo.film_actor_hash['Black Panther'] = [ danai_gurira, chadwick_boseman, michael_b_jordan, angela_bassett ]
mandy_patinkin.film_actor_hash['The Princess Bride'] = [ cary_elwes, robin_wright, billy_crystal, andre_the_giant ]
marc_anthony.film_actor_hash['Man on Fire'] = [ dakota_fanning, denzel_washington, radha_mitchell, christopher_walken ]
marcia_gay_harden.film_actor_hash['Fifty Shades of Grey'] = [ jamie_dornan, dakota_johnson, rita_ora, luke_grimes ]
mark_wahlberg.film_actor_hash['Transformers'] = [ tyrese_gibson, peter_cullen, josh_duhamel, shia_labeouf ]
martin_lawrence.film_actor_hash['Life'] = [ rick_james, eddie_murphy, bernie_mac, obba_babatunde ]
matt_damon.film_actor_hash['Good Will Hunting'] = [ robin_williams, casey_affleck, ben_affleck, minnie_driver ]
matthew_mcconaughey.film_actor_hash['A Time To Kill'] = [ sandra_bullock, octavia_spencer, samuel_l_jackson, kevin_spacey ]
mel_gibson.film_actor_hash['Lethal Weapon'] = [ mitchell_ryan, danny_glover, gary_busey, jackie_swanson ]
michael_b_jordan.film_actor_hash['Black Panther'] = [ danai_gurira, lupita_nyongo, chadwick_boseman, angela_bassett ]
michael_clarke_duncan.film_actor_hash['Armageddon'] = [ bruce_willis, liv_tyler, ben_affleck, steve_buscemi ]
michael_sheen.film_actor_hash['Underworld'] = [ kevin_grevioux, theo_james, scott_speedman, kate_beckinsale ]
michelle_trachtenberg.film_actor_hash['Ice Princess'] = [ kim_cattrall, hayden_panettiere, joan_cusack, erik_king ]
milla_jovovich.film_actor_hash['The Fifth Element'] = [ ian_holm, bruce_willis, gary_oldman, chris_tucker ]
minnie_driver.film_actor_hash['Good Will Hunting'] = [ matt_damon, robin_williams, casey_affleck, ben_affleck ]
mitchell_ryan.film_actor_hash['Lethal Weapon'] = [ mel_gibson, jackie_swanson, gary_busey, danny_glover ]
morris_chestnut.film_actor_hash['Boyz n the Hood'] = [ angela_bassett, cuba_gooding_jr, ice_cube, laurence_fishburne ]
natalie_portman.film_actor_hash['Heat'] = [ val_kilmer, robert_de_niro, ashley_judd, al_pacino ]
nbushe_wright.film_actor_hash['Dead Presidents'] = [ larenz_tate, chris_tucker, keith_david, terrence_howard ]
nicole_kidman.film_actor_hash['Batman Forever'] = [ tommy_lee_jones, jim_carrey, chris_odonnell, val_kilmer ]
nicole_kidman.film_actor_hash['Beguiled'] = [ collin_farrell, elle_fanning, kirsten_dunst, angourie_rice ]
obba_babatunde.film_actor_hash['Life'] = [ rick_james, martin_lawrence, bernie_mac, eddie_murphy ]
octavia_spencer.film_actor_hash['A Time To Kill'] = [ matthew_mcconaughey, sandra_bullock, samuel_l_jackson, kevin_spacey ]
olivia_williams.film_actor_hash['The Postman'] = [ larenz_tate, will_patton, kevin_costner, tom_petty ]
orlando_bloom.film_actor_hash['The Lord of the Rings'] = [ liv_tyler, viggo_mortensen, ian_holm, elijah_wood ]
patrick_swayze.film_actor_hash['Ghost'] = [ demi_moore, whoopi_goldberg, armelia_mcqueen, tony_goldwyn ]
paul_reubens.film_actor_hash['Flight of the Navigator'] = [ joey_cramer, raymond_forchion, sarah_jessica_parker, veronica_cartwright ]
peter_cullen.film_actor_hash['Transformers'] = [ josh_duhamel, mark_wahlberg, tyrese_gibson, shia_labeouf ]
queen_latifah.film_actor_hash['Beauty Shop'] = [ alicia_silverstone, kevin_bacon, djimon_hounsou, bryce_wilson ]
rachel_weisz.film_actor_hash['Constantine'] = [ djimon_hounsou, keanu_reeves, tilda_swinton, shia_labeouf ]
radha_mitchell.film_actor_hash['Man on Fire'] = [ dakota_fanning, denzel_washington, christopher_walken, marc_anthony ]
raymond_forchion.film_actor_hash['Flight of the Navigator'] = [ joey_cramer, sarah_jessica_parker, paul_reubens, veronica_cartwright ]
regina_king.film_actor_hash['Ray'] = [ bokeem_woodbine, kerry_washington, jamie_foxx, clifton_powell ]
rhona_mitra.film_actor_hash['Hallow Man'] = [ josh_brolin, elisabeth_shue, kevin_bacon, kim_dickens ]
rick_james.film_actor_hash['Life'] = [ eddie_murphy, martin_lawrence, bernie_mac, obba_babatunde ]
rita_ora.film_actor_hash['Fifty Shades of Grey'] = [ jamie_dornan, dakota_johnson, luke_grimes, marcia_gay_harden ]
robert_de_niro.film_actor_hash['Heat'] = [ ashley_judd, val_kilmer, al_pacino, natalie_portman ]
robert_de_niro.film_actor_hash['Sleepers'] = [ brad_pitt, kevin_bacon, dustin_hoffman, jason_patric ]
robert_pattinson.film_actor_hash['Twilight'] = [ billy_burke, kristen_stewart, taylor_lautner, ashley_green ]
robin_williams.film_actor_hash['Good Will Hunting'] = [ matt_damon, minnie_driver, ben_affleck, casey_affleck ]
robin_wright.film_actor_hash['The Princess Bride'] = [ andre_the_giant, cary_elwes, mandy_patinkin, billy_crystal ]
robin_wright.film_actor_hash['Wonder Woman'] = [ ann_wolfe, chris_pine, gal_gadot, connie_nielsen ]
ron_perlman.film_actor_hash['Blade'] = [ wesley_snipes, ryan_reynolds, kris_kristofferson, jessica_biel ]
ryan_reynolds.film_actor_hash['Blade'] = [ wesley_snipes, ron_perlman, kris_kristofferson, jessica_biel ]
samuel_l_jackson.film_actor_hash['A Time To Kill'] = [ octavia_spencer, sandra_bullock, matthew_mcconaughey, kevin_spacey ]
sandra_bullock.film_actor_hash['A Time To Kill'] = [ octavia_spencer, matthew_mcconaughey, samuel_l_jackson, kevin_spacey ]
sarah_jessica_parker.film_actor_hash['Flight of the Navigator'] = [ raymond_forchion, joey_cramer, paul_reubens, veronica_cartwright ]
scott_speedman.film_actor_hash['Underworld'] = [ kevin_grevioux, theo_james, kate_beckinsale, michael_sheen ]
shia_labeouf.film_actor_hash['Constantine'] = [ keanu_reeves, rachel_weisz, tilda_swinton, djimon_hounsou ]
shia_labeouf.film_actor_hash['Transformers'] = [ tyrese_gibson, mark_wahlberg, josh_duhamel, peter_cullen ]
steve_buscemi.film_actor_hash['Armageddon'] = [ michael_clarke_duncan, liv_tyler, ben_affleck, bruce_willis ]
taylor_lautner.film_actor_hash['Twilight'] = [ kristen_stewart, robert_pattinson, billy_burke, ashley_green ]
terrence_howard.film_actor_hash['Dead Presidents'] = [ larenz_tate, chris_tucker, keith_david, nbushe_wright ]
theo_james.film_actor_hash['Underworld'] = [ kevin_grevioux, kate_beckinsale, scott_speedman, michael_sheen ]
tilda_swinton.film_actor_hash['Constantine'] = [ keanu_reeves, rachel_weisz, shia_labeouf, djimon_hounsou ]
tom_cruise.film_actor_hash['Interview with the Vampire'] = [ kirsten_dunst, brad_pitt, christian_slater, antonio_banderas ]
tommy_lee_jones.film_actor_hash['Batman Forever'] = [ val_kilmer, jim_carrey, chris_odonnell, nicole_kidman ]
tommy_lee_jones.film_actor_hash['JFK'] = [ kevin_costner, gary_oldman, joe_pesci, walter_matthau ]
tom_petty.film_actor_hash['The Postman'] = [ larenz_tate, will_patton, olivia_williams, kevin_costner ]
tony_goldwyn.film_actor_hash['Ghost'] = [ demi_moore, patrick_swayze, whoopi_goldberg, armelia_mcqueen ]
tyrese_gibson.film_actor_hash['Transformers'] = [ peter_cullen, mark_wahlberg, josh_duhamel, shia_labeouf ]
val_kilmer.film_actor_hash['Batman Forever'] = [ tommy_lee_jones, jim_carrey, chris_odonnell, nicole_kidman ]
val_kilmer.film_actor_hash['Heat'] = [ robert_de_niro, ashley_judd, al_pacino, natalie_portman ]
veronica_cartwright.film_actor_hash['Flight of the Navigator'] = [ raymond_forchion, sarah_jessica_parker, paul_reubens, joey_cramer ]
viggo_mortensen.film_actor_hash['The Lord of the Rings'] = [ liv_tyler, orlando_bloom, ian_holm, elijah_wood ]
walter_matthau.film_actor_hash['JFK'] = [ kevin_costner, tommy_lee_jones, joe_pesci, gary_oldman ]
wesley_snipes.film_actor_hash['Blade'] = [ ryan_reynolds, ron_perlman, kris_kristofferson, jessica_biel ]
whoopi_goldberg.film_actor_hash['Ghost'] = [ demi_moore, patrick_swayze, tony_goldwyn, armelia_mcqueen ]
will_patton.film_actor_hash['The Postman'] = [ larenz_tate, kevin_costner, olivia_williams, tom_petty ]
woody_harrelson.film_actor_hash['The Hunger Games'] = [ jennifer_lawrence, liam_hemsworth, elizabeth_banks, donald_sutherland ]

puts graph.breadth_first_search(kevin_bacon, kevin_bacon)
print " \n "
puts graph.breadth_first_search(josh_brolin, kevin_bacon)
print " \n "
puts graph.breadth_first_search(chadwick_boseman, kevin_bacon)
print " \n "
puts graph.breadth_first_search(larenz_tate, kevin_bacon)
print " \n "
puts graph.breadth_first_search(shia_labeouf, kevin_bacon)
  